---
- name: make block
  block:
    - name: Install NCCL from CUDA repository for RHEL
      ansible.builtin.yum:
        name:
          - "libnccl-{{ nccl_package_version }}"
          - "libnccl-devel-{{ nccl_package_version }}"
          - "libnccl-static-{{ nccl_package_version }}"
        state: present
      environment: "{{ proxy_env if proxy_env is defined else {} }}"
      when:
        - ansible_os_family == 'RedHat'

    - name: Install NCCL from CUDA repository for Ubuntu
      ansible.builtin.apt:
        name:
          - "libnccl2={{ nccl_package_version }}"
          - "libnccl-dev={{ nccl_package_version }}"
        state: present
        lock_timeout: 300
      environment: "{{ proxy_env if proxy_env is defined else {} }}"
      when:
        - ansible_distribution == 'Ubuntu'
  rescue:
    - name: Set architecture for Arm
      ansible.builtin.set_fact:
        architecture: "arm64"
      when:
        - ansible_architecture == 'aarch64'

    - name: Set architecture for X86
      ansible.builtin.set_fact:
        architecture: "x86_64"
      when:
        - ansible_architecture == 'x86_64'

    - name: Download NCCL source
      get_url:
        url: "https://github.com/NVIDIA/nccl/archive/refs/tags/v{{ nccl_version }}.tar.gz"
        dest: "/tmp/v{{ nccl_version }}.tar.gz"
        mode: '0644'

    - name: Extract NCCL tarball
      ansible.builtin.unarchive:
        src: "/tmp/v{{ nccl_version }}.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Build NCCL Debian package
      community.general.make:
        chdir: "/tmp/nccl-{{ nccl_version }}"
        target: "pkg.debian.build"
        params:
          NUM_THREADS: "{{ ansible_processor_vcpus }}"
      when:
        - ansible_distribution == 'Ubuntu'

    - name: Build NCCL Debian package
      community.general.make:
        chdir: "/tmp/nccl-{{ nccl_version }}"
        target: "pkg.redhat.build"
        params:
          NUM_THREADS: "{{ ansible_processor_vcpus }}"

      when:
        - ansible_distribution == 'RedHat'

    - name: Install NCCL build dependencies on Debian/Ubuntu
      apt:
        name:
          - build-essential
          - devscripts
          - debhelper
          - fakeroot
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install NCCL from local build for Ubuntu
      ansible.builtin.apt:
        deb: "{{ item }}"
        state: present
        lock_timeout: 300
      with_items:
        - "/tmp/nccl-{{ nccl_version }}/build/pkg/deb/libnccl2_{{ nccl_package_version }}_{{ architecture }}.deb"
        - "/tmp/nccl-{{ nccl_version }}/build/pkg/deb/libnccl-dev_{{ nccl_package_version }}_{{ architecture }}.deb"
      when: ansible_distribution == 'Ubuntu'

    - name: Install NCCL from local build for RHEL
      yum:
        name:
          - "/tmp/nccl-{{ nccl_version }}/build/pkg/rpm//libnccl-{{ nccl_package_version }}.el{{ansible_distribution_major_version}}.{{architecture}}.rpm"
          - "/tmp/nccl-{{ nccl_version }}/build/pkg/rpm//libnccl-devel-{{ nccl_package_version }}.el{{ansible_distribution_major_version}}.{{architecture}}.rpm"
          - "/tmp/nccl-{{ nccl_version }}/build/pkg/rpm//libnccl-static-{{ nccl_package_version }}.el{{ansible_distribution_major_version}}.{{architecture}}.rpm"
        state: latest
        disable_gpg_check: true
      when: ansible_distribution == 'RedHat'
