---
- name: Disclaimer for AMD image
  when:
    - "'amd' in options"

  block:
    - name: Disclaimer for AMD image
      ansible.builtin.copy:
        src: README.txt
        dest: "/home/ubuntu/README.txt"
        owner: ubuntu
        group: ubuntu
        mode: "0644"
