---
- name: MFT RPM download
  ansible.builtin.set_fact:
    package_extension: "rpm"
  when:
    - ansible_os_family == 'RedHat'

- name: MTF DEB download
  ansible.builtin.set_fact:
    package_extension: "deb"
  when:
    - ansible_os_family == 'Debian'

- name: MFT RPM download
  ansible.builtin.set_fact:
    architecture: "arm64"
  when:
    - ansible_architecture == 'aarch64'

- name: MTF DEB download
  ansible.builtin.set_fact:
    architecture: "x86_64"
  when:
    - ansible_architecture == 'x86_64'

- name: Get DEB architecture # noqa no-changed-when
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture_output
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'x86_64'

- name: set deb_architecture
  ansible.builtin.set_fact:
    deb_architecture: "{{deb_architecture_output.stdout}}"
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'x86_64'

- name: set deb_architecture 
  ansible.builtin.set_fact:
    deb_architecture: "arm64"
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'aarch64'

- name: Extract Mellanox MFT installation tarball
  ansible.builtin.unarchive:
    src: "{{ mellanox_mft_download }}/{{ mft_version }}-{{ architecture }}-{{ package_extension }}.tgz"
    dest: /tmp
    remote_src: true

- name: Install Mellanox MFT update (yum/dnf)
  ansible.builtin.yum:
    name: "/tmp/{{ mft_version }}-{{ architecture }}-rpm/RPMS/{{ mft_version }}.{{ architecture }}.rpm"
    state: present
    disable_gpg_check: true
  when:
    - ansible_os_family == 'RedHat'

- name: Install mstflint
  ansible.builtin.yum:
    name: mstflint
  when: ansible_os_family == 'RedHat' and install_mstflint is defined and install_mstflint | bool

- name: Install mstflint
  ansible.builtin.apt:
    name: mstflint
    lock_timeout: 300
  when: ansible_os_family == 'Debian' and install_mstflint is defined and install_mstflint | bool

- name: Install Mellanox MFT update (apt)
  ansible.builtin.apt:
    deb: "/tmp/{{ mft_version }}-{{ architecture }}-deb/DEBS/{{ mft_version | replace('-', '_', 1) }}_{{ deb_architecture }}.deb"
    lock_timeout: 300
  when:
    - ansible_os_family == 'Debian'
