---
- name: Install mpivars
  when: >
    (ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '22' or ansible_distribution_major_version == '24')) or (ansible_os_family == 'RedHat' and (ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9'))
  block:
    - name: Get the openmpi version # noqa command-instead-of-shell no-changed-when
      ansible.builtin.find:
        paths: /usr/mpi/gcc
        patterns: "openmpi*"
        recurse: false
        file_type: directory
      register: openmpi
      failed_when: false

    - name: Check if mpivars.sh exists
      ansible.builtin.stat:
        path: "{{ openmpi.files[0].path }}/bin/mpivars.sh"
      register: mpivars
      when: openmpi.files | length > 0

    - name: Create mpivars.sh
      become: true
      ansible.builtin.template:
        src: mpivars.j2
        dest: "{{ openmpi.files[0].path }}/bin/mpivars.sh"
        force: true
        owner: root
        group: root
        mode: '0755'
      when: openmpi.files | length > 0 and not mpivars.stat.exists
