---
- name: OCA for Oracle Linux
  block:
    - name: Stop cloud agent
      service:
        name: oracle-cloud-agent
        state: stopped

    - name: Check if agent.yml exists
      stat:
        path: /etc/oracle-cloud-agent/agent.yml
      register: agent_file

    - name: Read the agent configuration
      slurp:
        path: /etc/oracle-cloud-agent/agent.yml
      register: r_myfile
      when: agent_file.stat.exists

    - name: extract the data
      set_fact:
        mydata: "{{ r_myfile['content'] | b64decode | from_yaml }}"
      when: agent_file.stat.exists

    - name: Create configuration for core - modify params
      set_fact:
        mydata: "{{ mydata | combine(newdata, recursive=True) }}"
      vars:
        newdata:
          plugins:
            osms:
              disabled: true
      when: agent_file.stat.exists

    - name: Write back to a file
      copy:
        content: '{{ mydata | to_nice_yaml }}'
        dest: /etc/oracle-cloud-agent/agent.yml
      when: agent_file.stat.exists

    - name: Restart cloud agent
      service:
        name: oracle-cloud-agent
        state: restarted
      when: agent_file.stat.exists

    - name: Unregister agent
      command: osms unregister
      when: agent_file.stat.exists

    # Present in OL images prior to May/June 2020, later replaced with oracle cloud agent
    - name: Check if osms-agent service exist
      shell: service osms-agent status
      register: osms_agent_status
      failed_when: not(osms_agent_status.rc == 3 or osms_agent_status.rc == 0 or osms_agent_status.rc == 4)

    - name: disable osms-agent.service
      service:
        name: osms-agent
        state: stopped
        enabled: no
      when: (osms_agent_status.rc == 0 or osms_agent_status.rc == 3)

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'OracleLinux'
    
# Disable updater.
# We do this so customers won't be impacted should the agent get upgraded when
# they don't expect it. Some of the plugins (e.g. HPC) can cause network or
# host configuration changes.
#
# The updater is disabled by editing the "/etc/oracle-cloud-agent/updater.yml"
# file.  The file looks like this:
#
# agent:
#   upgrade_interval: 3600
#   upgrade_init_delay: 3600
#   upgrade_init_jitter: 120
#   ...
#
# To disable updating, we change the "upgrade_interval" to -1
#
# There is no need to stop OCA when editing this file, but changes won't be
# picked up until a restart.

- name: Disable OCA updater
  block:
    - name: Read the agent configuration
      slurp:
        path: /etc/oracle-cloud-agent/updater.yml
      register: oca_updater_file_contents

    - name: extract the data
      set_fact:
        mydata: "{{ oca_updater_file_contents['content'] | b64decode | from_yaml }}"

    - name: Create configuration for core - modify params
      set_fact:
        mydata: "{{ mydata | combine(newdata, recursive=True) }}"
      vars:
        newdata:
          agent:
            upgrade_interval: -1

    - name: Write back to a file
      copy:
        content: '{{ mydata | to_nice_yaml }}'
        dest: /etc/oracle-cloud-agent/updater.yml
