- hosts: all
  any_errors_fatal: yes
  become: true

# options:
#   rhck - For OraceLinux install RedHat Compatiable Kernel
#   upgrade - Upgrade all packages to the latest
#   nomitigations - Disable all security mitigations
#   noselinux - Disable SELinux
#   nvidia - Install NVIDIA GPU drivers and software
#   monitoring - Install NVIDIA DCGM
#   benchmarks - Install benchmarks
#   intel-oneapi - Install Intel OneAPI MPI/MKL
#   openmpi - Install OpenMPI against system gcc
#   use_plugins - Do not install OCI HPC packages that are replaced by OCA HPC Plugins

# groups:
#   groups define the variables (group_vars) to use with the roles

  tasks:
    - import_role:
        name: oca
