---
- name: Packages for RHEL 7 and 8
  block:
    - name: Ensure Oracle Cloud Agent is stopped to prevent running yum
      systemd:
        name: '{{ item }}.service'
        state: stopped
      with_items:
        - oracle-cloud-agent
        - oracle-cloud-agent-updater

    - name: Unregister agent
      command: osms unregister

    - name: Ensure latest microcode_ctl is installed
      yum:
        name:
          - microcode_ctl
        state: latest

    - name: Ensure dracut early_microcode="yes" is configured
      lineinfile:
        path: /usr/lib/dracut/dracut.conf.d/01-microcode.conf
        regexp: '^early_microcode='
        line: 'early_microcode="yes"'
        create: no
        state: present

    - name: Unregister agent
      command: osms unregister

    - name: Install development tools
      yum:
        enablerepo: "*developer_EPEL*"
        name:
          - "@Development Tools"
          - numactl
          - numactl-devel
          - libxml2
          - binutils-devel
          - environment-modules
        state: present

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
#        nobest: yes
      when:
        - "options is defined"
        - "'upgrade' in options"

    - name: Hold linux-oracle
      ansible.builtin.dpkg_selections:
        name: linux-oracle
        selection: hold
      when: ansible_distribution == 'Ubuntu'

    - name: Reboot to install kernel updates
      reboot:
        reboot_timeout: 900
      when:
        - "options is defined"
        - "'upgrade' in options or 'rhck' in options"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'


- name: Packages for Ubuntu
  block:

    - name: Ensure Oracle Cloud Agent is stopped to prevent running apt
      systemd:
        name: snap.oracle-cloud-agent.oracle-cloud-agent
        state: stopped

    - name: Wait for automatic system updates to complete
      shell: while pgrep apt; do sleep 10; done;

    - name: Disable unattended-upgrades
      systemd:
        name: unattended-upgrades
        enabled: no
        state: stopped
        masked: yes

    - name: Remove unattended-upgrades
      apt:
        name: unattended-upgrades
        state: absent

    - name: Update apt repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 0

    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 0

    - name: Upgrade all packages
      apt:
        name: '*'
        state: latest
      when:
        - "options is defined"
        - "'upgrade' in options"

    - name: Install CMake
      apt:
        name: cmake
        state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Kernel downgrade for Ubuntu 22
  block:

    # Prefer the generic kernel flavor over oracle *before* we install the
    # generic kernel flavor so update-grub pick it during installation.
    - name: prefer the generic kernel flavor over oracle
      lineinfile:
        path: /etc/default/grub.d/10_linux_flavour.cfg
        create: yes
        regexp: '^GRUB_FLAVOUR_ORDER='
        line: 'GRUB_FLAVOUR_ORDER="generic"'

    - name: install linux-image-generic
      apt:
        name:
        - 'linux-image-generic'
        - 'linux-headers-generic'
        state: latest

    - name: Reboot to install kernel updates
      reboot:
        reboot_timeout: 900

    - name: remove linux-image-*-oracle kernel for 6.5 and 6.8
      apt:
        name:
        - 'linux-image-oracle'
        - 'linux-image-6.5.0-*-oracle'
        - 'linux-image-6.8.0-*-oracle'
        - 'linux-image-unsigned-6.5.0-*-oracle'
        - 'linux-image-unsigned-6.8.0-*-oracle'
        - 'linux-modules-6.5.0-*-oracle'
        - 'linux-modules-6.8.0-*-oracle'
        - 'linux-modules-extra-6.5.0-*-oracle'
        - 'linux-modules-extra-6.8.0-*-oracle'
        - 'linux-headers-6.5.0-*-oracle'
        - 'linux-headers-6.8.0-*-oracle'
        - 'linux-oracle-6.5-headers-6.5.0-*'
        - 'linux-oracle-6.8-headers-6.8.0-*'
        autoremove: yes
        state: absent

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'


- name: Kernel changes AMD
  block:

    - name: install linux-image-5.15.0-91-generic
      apt:
        name: 'linux-image-5.15.0-91-generic'
        state: latest

    - name: remove linux-image-6.5.0-1020-oracle
      apt:
        name: 'linux-image-6.5.0-1020-oracle'
        state: absent

    - name: delete 6.5.0
      shell: |
        rm initrd.img
        rm vmlinuz
        rm -f *6.5.0*
        rm initrd.img.old
        rm vmlinuz.old
        ln -sf initrd.img-5.15.0-91-generic initrd.img
        ln -sf vmlinuz-5.15.0-91-generic vmlinuz
        ls -lat
      args:
        chdir: "/boot"


    - name: sleep
      command:
        cmd: "sleep 30"
      args:
        chdir: "/boot"

    - name: Update grub
      command:
        cmd: "update-grub"
      args:
        chdir: "/boot"

    - name: sleep
      command:
        cmd: "sleep 30"
      args:
        chdir: "/boot"

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
    - "'amd' in options"



- name: Remaining Packages for Ubuntu
  block:

    - name: Reboot to install kernel updates
      reboot:
        reboot_timeout: 900
      when:
        - "options is defined"
        - "'upgrade' in options"

    - name: Ensure Oracle Cloud Agent is stopped to prevent running apt
      systemd:
        name: snap.oracle-cloud-agent.oracle-cloud-agent
        state: stopped

    - name: Wait for automatic system updates to complete
      shell: while pgrep apt; do sleep 10; done;

    - name: install numactl
      apt:
        name: 'numactl'
        state: latest
  when:
    - ansible_distribution == 'Ubuntu'



- name: Remove linux-image to stop kernel updates
  block:

    - name: remove linux-image-generic to stop kernel updates
      apt:
        name: 'linux-image-generic'
        state: absent

    - name: remove linux-image to stop kernel updates
      apt:
        name: 'linux-image'
        state: absent


  when:
    - ansible_distribution == 'Ubuntu'



- name: Install oci-cli
  block:
    - name: Create "/opt/oci-hpc/oci-cli" directory
      file:
        path: /opt/oci-hpc/oci-cli
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: install oci-cli
      get_url:
        url: https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
        dest: "/opt/oci-hpc/oci-cli"
      register: oci_cli_installer

    - name: install oci-cli --accept-all-defaults
      shell: |
        bash {{ oci_cli_installer.dest }} --install-dir "${HOME}/lib/oracle-cli" --script-dir "${HOME}/lib/oci-cli-scripts" --accept-all-defaults
      args:
        chdir: "/opt/oci-hpc/oci-cli"
      become: true
      become_user: ubuntu

    - name: Remove oci-cli installer
      file:
        path: /opt/oci-hpc/oci-cli
        state: absent

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'


- name: Edit the rdma_network.json file
  block:
    - name: Edit the rdma_network.json file
      copy:
        src: 'rdma_network.json'
        dest: '/etc/oracle-cloud-agent/plugins/oci-hpc/oci-hpc-configure/rdma_network.json'

- name: Additional packages AMD
  block:

    - name: Install jq
      apt:
        name: jq

    - name: Install pdsh
      apt:
        name: pdsh

    - name: Install unzip
      apt:
        name: unzip

    - name: Install apt-get alien
      apt:
        name: alien
        force_apt_get: yes

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
    - "'amd' in options"


- name: AMD changes for gc_thresh settings
  block:
    - name: Change gc_thresh settings
      copy:
        dest: "/etc/sysctl.d/80-oci-amd-tuning.conf"
        content: |
          net.ipv4.neigh.default.gc_thresh1=32768
          net.ipv4.neigh.default.gc_thresh2=65535
          net.ipv4.neigh.default.gc_thresh3=131072
    - name: Run sysctl
      shell: "sysctl -p"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'


- name: AMD changes for iptables
  block:
    - name: stop and disable ufw
      shell: |
        systemctl disable --now ufw
      args:
        chdir: "/tmp"

    - name: iptables -L
      shell: |
        iptables -L
      args:
        chdir: "/tmp"

    - name: iptables -F
      shell: |
        iptables -F
      args:
        chdir: "/tmp"

    - name: iptables save rules.v4
      shell: |
        iptables-save > /etc/iptables/rules.v4
      args:
        chdir: "/tmp"

    - name: iptables-save ptables.rules
      shell: |
        iptables-save > /etc/network/iptables.rules
      args:
        chdir: "/tmp"

    - name: netfilter-persistent save
      shell: |
        netfilter-persistent save
      args:
        chdir: "/tmp"

    - name: netfilter-persistent reload
      shell: |
        netfilter-persistent reload
      args:
        chdir: "/tmp"

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
    - "'amd' in options"

