---
- name: ROCM for EL
  when:
    - ansible_os_family == 'RedHat'
  block:

    - name: Set major.minor version
      ansible.builtin.set_fact:
        os_version: "{{ (ansible_distribution_version | split('.'))[0] }}.{{ (ansible_distribution_version | split('.'))[1] }}"

    - name: Download sources
      ansible.builtin.get_url:
        url: "{{ amd_rocm_repo }}/{{ amd_rocm_version }}/el/{{ os_version }}/amdgpu-install-{{ amd_rocm_package_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
        dest: /tmp
        mode: '0755'
      register: amd_rocm_tmp_archive

    - name: Import GPG key for AMDGPU
      ansible.builtin.rpm_key:
        key: "https://repo.radeon.com/rocm/rocm.gpg.key"
        state: present
        
    - name: Install amdgpu
      ansible.builtin.yum:
        name: "{{ amd_rocm_tmp_archive.dest }}"
        lock_timeout: 300

    - name: Run amdgpu-install # noqa no-changed-when
      ansible.builtin.shell: |
        amdgpu-install -y --usecase=graphics,rocm
      args:
        chdir: "/tmp"

- name: Add default user to render and video groups
  block:
    - name: Add ubuntu to render and video groups
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: render,video
        append: true
