- name: Install AMD ROCm on Ubuntu
  ansible.builtin.include_tasks:
    file: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install AMD ROCm on Oracle Linux
  ansible.builtin.include_tasks:
    file: el.yml
  when: ansible_os_family == 'RedHat'
