---
- name: Download AMD ROCm Repository GPG key
  become: true
  ansible.builtin.get_url:
    url: "{{ amd_rocm_ubuntu_repo_gpgkey_url }}"
    dest: /tmp/amd_rocm.asc.gpg
    mode: '0644'
    force: true
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
- name: Convert key to binary keyring
  become: true
  ansible.builtin.command:
    cmd: "gpg --dearmor -o /etc/apt/keyrings/amd_rocm.gpg /tmp/amd_rocm.asc.gpg"
    creates: /etc/apt/keyrings/amd_rocm.gpg
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Add AMD drivers repository
  ansible.builtin.apt_repository:
    #e.g. deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/30.20.1/ubuntu noble main
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/amd_rocm.gpg] {{ amd_dkms_repo_baseurl }}/{{ amd_dkms_version }}/ubuntu {{ ansible_facts['distribution_release'] }} main"
    update_cache: true
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
- name: Add AMD ROCm repository
  ansible.builtin.apt_repository:
    #e.g. deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/7.1.1 noble main
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/amd_rocm.gpg] {{ amd_rocm_repo_baseurl }}/apt//{{ amd_rocm_version }} {{ ansible_facts['distribution_release'] }} main"
    update_cache: true
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
- name: Add AMD graphics repository
  ansible.builtin.apt_repository:
    #e.g. deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/graphics/7.1.1/ubuntu noble main
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/amd_rocm.gpg] {{ amd_graphics_repo_baseurl }}/{{ amd_rocm_version }}/ubuntu {{ ansible_facts['distribution_release'] }} main"
    update_cache: true
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when: amd_rocm_version is version('7.0', '>=')
- name: Add AMD repository for amdgpu-lib
  ansible.builtin.apt_repository:
    #e.g. deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/6.4.3/ubuntu noble main
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/amd_rocm.gpg] {{ amd_dkms_repo_baseurl }}/{{ amd_rocm_version }}/ubuntu {{ ansible_facts['distribution_release'] }} main"
    update_cache: true
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when: amd_rocm_version is version('7.0', '<')

- name: Pin AMD ROCm repositories in APT preferences
  copy:
    dest: /etc/apt/preferences.d/amd_rocm_pin
    content: |
      Package: *
      Pin: origin repo.radeon.com
      Pin-Priority: 600
    owner: root
    group: root
    mode: '0644'

- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    lock_timeout: 300

- name: Check if the kernel is pinned by 00_pin_kernel
  ansible.builtin.stat:
    path: /etc/apt/preferences.d/00_pin_kernel
  register: pinned_kernel

- name: Temporarly remove pinning file to allow for the Install
  ansible.builtin.file:
    path: /etc/apt/preferences.d/00_pin_kernel
    state: absent
  when: pinned_kernel.stat.exists

- name: Install AMD driver package
  ansible.builtin.apt:
    name:
      - "amdgpu-dkms"
    state: "present"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Pin the kernel packages again
  ansible.builtin.copy:
    content: |
      Package: linux-*
      Pin: version *
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/00_pin_kernel
    mode: "0644"
  when: pinned_kernel.stat.exists

- name: Reboot after driver install
  ansible.builtin.reboot:
    reboot_timeout: 900
    post_reboot_delay: 30

- name: Install AMD ROCm packages
  ansible.builtin.apt:
    name:
      - "rocm"
      - "amdgpu-lib"
    state: "present"
    lock_timeout: 300
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Add default user to render and video groups
  block:
    - name: Add ubuntu to render and video groups
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: render,video
        append: true
