---
- name: ROCM for Ubuntu 22
  block:

    - name: download sources
      get_url:
        url: "{{ amd_rocm_ubuntu22_url }}"
        dest: /tmp
      register: amd_rocm_tmp_archive

    - name: install headers using meta package
      apt:
        pkg:
          - linux-headers-generic

    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: install amdgpu
      apt:
        deb: "{{ amd_rocm_tmp_archive.dest }}"

    - name: Run amdgpu-install
      shell: |
        yes | amdgpu-install --usecase=graphics,rocm
      args:
        chdir: "/tmp"


    - name: Reboot to install kernel updates
      reboot:
        reboot_timeout: 900

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'


- name: Add ubuntu to render and video groups
  block:
    - name: Add ubuntu to render and video groups
      shell: |
        usermod -a -G render,video ubuntu
      args:
        chdir: "/tmp"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
