---
- name: Install OpenSCAP
  apt:
    name: libopenscap8
    state: present

- name: Install bzip2
  apt:
    name: bzip2
    state: present

- name: Download and unpack oval data
  get_url:
    url: "https://security-metadata.canonical.com/oval/com.ubuntu.{{ ansible_distribution_release  }}.usn.oval.xml.bz2"
    dest: /tmp/oval-usn.xml.bz2

- name: Decompress oval data
  command: bunzip2 /tmp/oval-usn.xml.bz2
  args:
    creates: /tmp/oval-usn.xml

- name: Configure and Run OpenScAP
  command: oscap oval eval --results /tmp/oscap_report.xml --report /tmp/oscap_report.html /tmp/oval-usn.xml
  register: oscap_stdout

- name: Check if vulnerabilites were found
  shell: grep 'result="fail"' /tmp/oscap_report.xml || true
  register: vulnerabilities_found

- name: Fail on vulnerabilities
  fail:
    msg: "Vulnerabilities were discovered in the image"
  when:
    vulnerabilities_found.stdout != ""

- name: Fetch Report
  fetch:
    src: /tmp/oscap_report.html
    dest: /tmp/oval-reports/
    flat: yes
