---

- name: Configure RHCK
  ansible.builtin.include_tasks: rhck.yml
  when:
    - "options is defined"
    - "'rhck' in options"
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'OracleLinux'

- name: Configure Ubuntu 22 Kernel
  ansible.builtin.include_tasks: ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
    - ubuntu_22_kernel_version is defined

- name: Configure Ubuntu 24 Kernel
  ansible.builtin.include_tasks: ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '24'
    - ubuntu_24_kernel_version is defined