---
- name: Packages for RHEL based systems
  when:
    - ansible_os_family == 'RedHat'

  block:
    - name: Ensure Oracle Cloud Agent is stopped to prevent running yum
      ansible.builtin.systemd:
        name: '{{ item }}.service'
        state: stopped
      with_items:
        - oracle-cloud-agent
        - oracle-cloud-agent-updater

    - name: Ensure latest microcode_ctl is installed
      ansible.builtin.dnf:
        name:
          - microcode_ctl
        state: present

    - name: Ensure dracut early_microcode="yes" is configured
      ansible.builtin.lineinfile:
        path: /usr/lib/dracut/dracut.conf.d/01-microcode.conf
        regexp: '^early_microcode='
        line: 'early_microcode="yes"'
        create: false
        state: present

    - name: Install development tools
      ansible.builtin.dnf:
        enablerepo: "*developer_EPEL*"
        name:
          - "@Development Tools"
          - numactl
          - numactl-devel
          - libxml2
          - binutils-devel
          - environment-modules
        state: present

    - name: Upgrade all packages # noqa package-latest
      ansible.builtin.dnf:
        name: '*'
        state: latest
      when:
        - "options is defined"
        - "'upgrade' in options"

    - name: Reboot to install kernel updates
      ansible.builtin.reboot:
        reboot_timeout: 900
      when:
        - "options is defined"
        - "'upgrade' in options or 'rhck' in options"

- name: Packages for Ubuntu
  when:
    - ansible_distribution == 'Ubuntu'

  block:

    - name: Ensure Oracle Cloud Agent is stopped to prevent running apt
      ansible.builtin.systemd:
        name: snap.oracle-cloud-agent.oracle-cloud-agent
        state: stopped

    - name: Wait for automatic system updates to complete
      ansible.builtin.shell: while pgrep apt; do sleep 10; done;
      changed_when: false

    - name: Disable unattended-upgrades
      ansible.builtin.systemd:
        name: unattended-upgrades
        enabled: false
        state: stopped
        masked: true

    - name: Remove unattended-upgrades
      ansible.builtin.apt:
        name: unattended-upgrades
        state: absent

    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0

    - name: Update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 0

    - name: Upgrade all packages # noqa package-latest
      ansible.builtin.apt:
        name: '*'
        state: latest
      when:
        - options is defined and 'upgrade' in options

    - name: Install CMake
      ansible.builtin.apt:
        name: cmake
        state: present
