mellanox_hpcx_version: "v2.18.1"
rhel7_mellanox_hpcx_package: "hpcx-v2.18.1-gcc-mlnx_ofed-redhat7-cuda12-{{ ansible_architecture }}"
rhel8_mellanox_hpcx_package: "hpcx-v2.18.1-gcc-mlnx_ofed-redhat8-cuda12-{{ ansible_architecture }}"
rhel9_mellanox_hpcx_package: "hpcx-v2.18.1-gcc-mlnx_ofed-redhat9-cuda12-{{ ansible_architecture }}"
ubuntu20_mellanox_hpcx_package: "hpcx-v2.18.1-gcc-mlnx_ofed-ubuntu20.04-cuda12-{{ ansible_architecture }}"
ubuntu22_mellanox_hpcx_package: "hpcx-v2.18.1-gcc-mlnx_ofed-ubuntu22.04-cuda12-{{ ansible_architecture }}"
mellanox_hpcx_download_url: "https://content.mellanox.com/hpc/hpc-x/{{ mellanox_hpcx_version }}"
