oci_cloud_agent_version_ubuntu: 1.55.0-1311
oca_download_url: >-
  https://objectstorage.ap-sydney-1.oraclecloud.com/p/oZcXnKCJZrs300xcrUNhr1gAeYisecp8a0tiW6Ppf7z3FiBOdHHkvEDtmISPtOkh/n/imagegen/b/JA-Test-DS/o/