oci_cloud_agent_version_ubuntu: 1.61.0-4139
oca_download_url: >-
  https://idxzjcdglx2s.objectstorage.eu-frankfurt-1.oci.customer-oci.com/p/OQvygv5RFpv_doxuiOEq0TRV4WE-U_FrAmZU9FbKPuXjXF28G3zUxIfk0-9P0-Uy/n/idxzjcdglx2s/b/packages/o/oca/
