---

- name: Configure RHCK
  ansible.builtin.include_tasks: rhck.yml
  when:
    - "options is defined"
    - "'rhck' in options"
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'OracleLinux'
