amd_rocm_ubuntu_repo_gpgkey_url: "https://repo.radeon.com/rocm/rocm.gpg.key"
amd_dkms_ubuntu_repo_baseurl: "https://repo.radeon.com/amdgpu"
amd_rocm_ubuntu_repo_baseurl: "https://repo.radeon.com/rocm/apt"
amd_graphics_ubuntu_repo_baseurl: "https://repo.radeon.com/graphics/"
