---
- name: Install openmpi
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
  block:
    - name: Install openmpi-bin
      ansible.builtin.apt:
        name: openmpi-bin

    - name: Install openmpi-common
      ansible.builtin.apt:
        name: openmpi-common

    - name: Install libopenmpi-dev
      ansible.builtin.apt:
        name: libopenmpi-dev
