---

- name: Ensure monitoring directory exists
  file:
    path: "{{ benchmark_base_path }}/oci-tuner/"
    state: directory
    owner: 'opc'
    group: 'opc'
  when: ansible_distribution == 'OracleLinux'

- name: Ensure monitoring directory exists
  file:
    path: "{{ benchmark_base_path }}/oci-tuner/"
    state: directory
    owner: 'ubuntu'
    group: 'ubuntu'
  when: ansible_distribution == 'Ubuntu'


- name: copy libnccl-ocituner for OL
  become: true
  get_url:
    url: https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/m1Gdcbiguqst6n_aVwRZIFpRZxUG-wGMvqWS5QJeJbIvNZnqTTA3N1_DDRuYpvJx/n/hpc/b/source/o/tuner/libnccl-ocituner.so.{{item}}_OL
    dest: "{{ benchmark_base_path }}/oci-tuner/libnccl-ocituner-A100.so.{{item}}"
    owner: opc
    group: opc
    mode: '0775'
  when: ansible_distribution == 'OracleLinux'
  with_items: 
    - "1.0.2"
    - "2.0.1"

- name: copy libnccl-ocituner for Ubuntu
  become: true
  get_url:
    url: https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/m1Gdcbiguqst6n_aVwRZIFpRZxUG-wGMvqWS5QJeJbIvNZnqTTA3N1_DDRuYpvJx/n/hpc/b/source/o/tuner/libnccl-ocituner.so.{{item}}_ubuntu_22.04
    dest: "{{ benchmark_base_path }}/oci-tuner/libnccl-ocituner-A100.so.{{item}}"
    owner: ubuntu
    group: ubuntu
    mode: '0775'
  when: ansible_os_family == 'Debian'
  with_items: 
    - "1.0.2"
    - "2.0.1"
