---
- name: NVIDIA CUDNN for Redhat
  block:

    - name: Install Nvidia CUDNN for RedHat
      yum:
        name:
          - libcudnn8
          - libcudnn8-devel

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'


- name: NVIDIA CUDNN for Ubuntu
  block:

    - name: Install Nvidia CUDNN for Ubuntu
      apt:
        name:
          - libcudnn8
          - libcudnn8-dev

  when:
    - ansible_distribution == 'Ubuntu'
