---
- name: Install rccl tests
  block:
    - name: Clone rccl github repository
      git:
        repo: https://github.com/ROCm/rccl.git
        dest: /opt/rccl
        clone: yes
        update: yes


    - name: Creates /opt/rccl/build directory
      ansible.builtin.file:
        path: /opt/rccl/build
        state: directory

    - name: install cmake
      apt:
        name: cmake

    - name: Install libstdc
      apt:
        name: libstdc++-12-dev

    - name: Set up CXX
      shell: |
        CXX=/opt/rocm/bin/hipcc cmake -DCMAKE_PREFIX_PATH=/opt/rocm/ ..
      args:
        chdir: "/opt/rccl/build"

    - name: make rccl
      shell: |
        make -j 16
      args:
        chdir: "/opt/rccl/build"


    - name: Clone rccl tests
      git:
        repo: https://github.com/ROCm/rccl-tests.git
        dest: /opt/rccl-tests
        clone: yes
        update: yes

    - name: make rccl
      shell: |
        make MPI=1 MPI_HOME=/usr/mpi/gcc/openmpi-4.1.5rc2 RCCL_HOME=/opt/rccl
      args:
        chdir: "/opt/rccl-tests"


  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
