---
- name: ROCM for Ubuntu 22
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
  block:

    - name: Download sources
      ansible.builtin.get_url:
        url: "{{ amd_rocm_ubuntu22_url }}"
        dest: /tmp
        mode: '0755'
      register: amd_rocm_tmp_archive

    - name: Install headers using meta package
      ansible.builtin.apt:
        pkg:
          - linux-headers-generic

    - name: Update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Install amdgpu
      ansible.builtin.apt:
        deb: "{{ amd_rocm_tmp_archive.dest }}"

    - name: Run amdgpu-install # noqa no-changed-when
      ansible.builtin.shell: |
        set -o pipefail
        yes | amdgpu-install --usecase=graphics,rocm
      args:
        chdir: "/tmp"

    - name: Reboot to install kernel updates
      ansible.builtin.reboot:
        reboot_timeout: 900

- name: Add ubuntu to render and video groups
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
  block:
    - name: Add ubuntu to render and video groups
      ansible.builtin.user:
        name: ubuntu
        groups: render,video
        append: true
