    # options:
    #   rhck - For OraceLinux install RedHat Compatiable Kernel
    #   upgrade - Upgrade all packages to the latest
    #   nomitigations - Disable all security mitigations
    #   noselinux - Disable SELinux
    #   nvidia - Install NVIDIA GPU drivers and software
    #   monitoring - Install NVIDIA DCGM
    #   benchmarks - Install benchmarks
    #   intel-oneapi - Install Intel OneAPI MPI/MKL
    #   openmpi - Install OpenMPI against system gcc
    #   use_plugins - Do not install OCI HPC packages that are replaced by OCA HPC Plugins

    # groups:
    #   groups define the variables (group_vars) to use with the roles

- name: AMD configuration
  hosts: all
  any_errors_fatal: true
  become: true
  tasks:
    - ansible.builtin.import_role: # noqa name[missing]
        name: amd_mpivars
      when: "'amd' in options"
    - ansible.builtin.import_role: # noqa name[missing]
        name: amd_rocm
      when: "'amd' in options"
    - ansible.builtin.import_role: # noqa name[missing]
        name: amd_perftest
      when: "'amd' in options"
    - ansible.builtin.import_role: # noqa name[missing]
        name: amd_rvs
      when: "'amd' in options"
    - ansible.builtin.import_role: # noqa name[missing]
        name: amd_disclaimer
      when: "'amd' in options"
    - ansible.builtin.import_role: # noqa name[missing]
        name: amd_rccl_tests
      when: "'amd' in options"


