---
- name: Edit the shapes.json
  block:
#    - name: Edit the shapes.json file
          #      copy:
          #        src: 'shapes.json'
          #        dest: '/etc/oracle-cloud-agent/plugins/oci-hpc/oci-hpc-configure/shapes.json'
          #      when: ansible_os_family == 'RedHat'
          #    - name: Edit the shapes.json file
          #      copy:
          #        src: 'shapes_ubuntu.json'
          #        dest: '/etc/oracle-cloud-agent/plugins/oci-hpc/oci-hpc-configure/shapes.json'
          #      when : ansible_distribution == 'Ubuntu'
    - name: Edit the shapes.json file
      copy:
        src: 'rdma_network.json'
        dest: '/etc/oracle-cloud-agent/plugins/oci-hpc/oci-hpc-configure/rdma_network.json'
      when: ansible_os_family == 'RedHat'
    - name: Edit the shapes.json file
      copy:
        src: 'rdma_network_ubuntu.json'
        dest: '/etc/oracle-cloud-agent/plugins/oci-hpc/oci-hpc-configure/rdma_network.json'
      when : ansible_distribution == 'Ubuntu'

    - name: Install latest OCA for OL
      yum:
        name: oracle-cloud-agent 
        state: latest
        disable_gpg_check: yes
      when:
        - ansible_os_family == 'RedHat'
    - name: Install yum-plugin-versionlock for OL7
      yum:
        name: yum-plugin-versionlock
        state: latest
        disable_gpg_check: yes
      when:
        - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
    - name: Install yum-plugin-versionlock for OL8
      yum:
        name: python3-dnf-plugin-versionlock
        state: latest
        disable_gpg_check: yes
      when:
        - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

    - name: Hold latest OCA for OL
      community.general.yum_versionlock:
        name: oracle-cloud-agent
        state: present
      when:
        - ansible_os_family == 'RedHat'

    - name: Snap update
      shell: "sudo snap refresh --channel=latest/edge oracle-cloud-agent"
      when : ansible_distribution == 'Ubuntu'

    - name: Hold Oracle cloud-agent
      shell: "sudo snap refresh --hold=forever oracle-cloud-agent"
      when : ansible_distribution == 'Ubuntu'

  when: "'use_plugins' in options"
