---
- name: Install NVIDIA fabric manager for RHEL 7
  yum:
    name: nvidia-fabricmanager-{{ nvidia_driver_version }}
    state: latest
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: Install NVIDIA fabric manager for RHEL 8
  dnf:
    name: nvidia-fabricmanager-{{ nvidia_driver_version }}
    state: latest
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '8'

- name: Install NVIDIA fabric manager for Ubuntu
  apt:
    name: nvidia-fabricmanager-{{ nvidia_driver_version }}
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Enable NVIDIA fabric manager service
  systemd:
    name: nvidia-fabricmanager
    enabled: yes
