- name: Change upgrade_interval for Oracle Cloud Agent Updater
  ansible.builtin.replace:
    path: /etc/oracle-cloud-agent/updater.yml
    regexp: 'upgrade_interval: 3600'
    replace: 'upgrade_interval: -1'
