---
- name: Disclaimer for AMD image
  block:
    - name: Disclaimer for AMD image
      copy:
        src: README.txt
        dest: "/home/ubuntu/README.txt"
        owner: ubuntu
        group: ubuntu
        mode: 0644

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
    - "'amd' in options"
