---
- name: Kernel boot parameters for RedHat 7 and 8
  block:
    - name: Run dracut -f
      shell: "sudo dracut -f"
      register: dracut_output

    - name: Reboot to install kernel updates
      become: true
      reboot:
        reboot_timeout: 900

    - name: Run dracut -f
      shell: "sudo dracut -f"
      register: dracut_output

    - name: Reboot to install kernel updates
      become: true
      reboot:
        reboot_timeout: 900
  when:
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'
